services:
  - type: web
    name: animacao-rotas-app
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: Maps_API_KEY # Chave da API do Google Maps (manter segura!)
        sync: false # Importante: não sincronizar com o Git, configurar diretamente no Render
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true # Gerar uma chave secreta automaticamente